# Connecting Python and SQL

## Working with 'absenteeism_module'

In [1]:
from absenteeism_module import *

In [2]:
pd.read_csv("Absenteeism_new_data.csv")

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0
5,28,11,11/06/2018,225,26,28,237.656,24,1,1,2
6,16,7,13/06/2018,118,15,46,275.089,25,1,2,0
7,22,27,13/06/2018,179,26,30,275.089,19,3,0,0
8,34,26,15/06/2018,118,10,37,275.089,28,1,0,0
9,34,10,20/06/2018,118,10,37,275.089,28,1,0,0
10,23,22,21/06/2018,378,49,36,275.089,21,1,2,4
11,36,19,21/06/2018,118,13,50,275.089,31,1,1,0
12,12,19,22/06/2018,233,51,31,275.089,21,2,1,8
13,22,27,22/06/2018,179,26,30,275.089,19,3,0,0
14,2,0,25/06/2018,235,29,48,275.089,33,1,1,5
15,21,0,28/06/2018,268,11,33,275.089,25,2,0,0
16,36,19,28/06/2018,118,13,50,275.089,31,1,1,0
17,22,13,28/06/2018,179,26,30,275.089,19,3,0,0
18,15,28,28/06/2018,291,31,40,275.089,25,1,1,1
19,22,13,02/07/2018,179,26,30,275.089,19,3,0,0
20,34,25,02/07/2018,118,10,37,275.089,28,1,0,0
21,12,22,05/07/2018,233,51,31,275.089,21,2,1,8
22,34,8,06/07/2018,118,10,37,275.089,28,1,0,0
23,34,10,11/07/2018,118,10,37,275.089,28,1,0,0
24,12,22,11/07/2018,233,51,31,275.089,21,2,1,8
25,5,26,11/07/2018,235,20,43,264.604,38,1,1,0
26,12,19,13/07/2018,233,51,31,264.604,21,2,1,8
27,9,6,16/07/2018,228,14,58,264.604,22,1,2,1
28,34,28,16/07/2018,118,10,37,264.604,28,1,0,0
29,9,6,17/07/2018,228,14,58,264.604,22,1,2,1
30,6,22,17/07/2018,189,29,33,264.604,25,1,2,2
31,34,23,18/07/2018,118,10,37,264.604,28,1,0,0
32,10,22,18/07/2018,361,52,28,264.604,27,1,1,4
33,28,22,18/07/2018,225,26,28,264.604,24,1,1,2
34,13,13,23/07/2018,369,17,31,264.604,25,1,3,0
35,11,14,24/07/2018,289,36,33,264.604,30,1,2,1
36,1,11,24/07/2018,235,11,37,264.604,29,3,1,1
37,4,0,24/07/2018,118,14,40,271.219,34,1,1,8
38,8,0,25/07/2018,231,35,39,271.219,35,1,2,2
39,35,0,27/07/2018,179,45,53,271.219,25,1,1,1

* `model` file is a file containing a fine-tuned finalized version of the logistic regression model

* `scaler` file contains the statistical parameters needed to adjust the magnitude of all numbers we have in this data set

In [3]:
model = absenteeism_model('model', 'scaler')

In [4]:
model.load_and_clean_data('Absenteeism_new_data.csv')

* `.predicted_outputs()` - its role is to feed the cleaned data into the model, and deliver the output we discussed

In [5]:
model.predicted_outputs()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet,Probability,Prediction
0,False,0.0,False,True,6,179,30,19,1,0,0,0.099575,0
1,True,0.0,False,False,6,361,28,27,0,1,4,0.897216,1
2,False,0.0,False,True,6,155,34,25,0,2,0,0.256719,0
3,False,0.0,False,True,6,179,40,22,1,2,0,0.167495,0
4,True,0.0,False,False,6,155,34,25,0,2,0,0.738584,1
5,True,0.0,False,False,6,225,28,24,0,1,2,0.734205,1
6,True,0.0,False,False,6,118,46,25,0,2,0,0.564198,1
7,False,0.0,False,True,6,179,30,19,1,0,0,0.099575,0
8,False,0.0,False,True,6,118,37,28,0,0,0,0.118777,0
9,True,0.0,False,False,6,118,37,28,0,0,0,0.524395,1
10,False,0.0,False,True,6,378,36,21,0,2,4,0.466122,0
11,False,0.0,True,False,6,118,50,31,0,1,0,0.718848,1
12,False,0.0,True,False,6,233,31,21,1,1,8,0.362669,0
13,False,0.0,False,True,6,179,30,19,1,0,0,0.099575,0
14,False,0.0,False,False,6,235,48,33,0,1,5,0.012456,0
15,False,0.0,False,False,6,268,33,25,1,0,0,0.028986,0
16,False,0.0,True,False,6,118,50,31,0,1,0,0.718848,1
17,True,0.0,False,False,6,179,30,19,1,0,0,0.474962,0
18,False,0.0,False,True,6,291,40,25,0,1,1,0.399885,0
19,True,0.0,False,False,7,179,30,19,1,0,0,0.476436,0
20,False,0.0,False,True,7,118,37,28,0,0,0,0.119398,0
21,False,0.0,False,True,7,233,31,21,1,1,8,0.034260,0
22,True,0.0,False,False,7,118,37,28,0,0,0,0.525869,1
23,True,0.0,False,False,7,118,37,28,0,0,0,0.525869,1
24,False,0.0,False,True,7,233,31,21,1,1,8,0.034260,0
25,False,0.0,False,True,7,235,43,38,0,1,0,0.548212,1
26,False,0.0,True,False,7,233,31,21,1,1,8,0.364037,0
27,True,0.0,False,False,7,228,58,22,0,2,1,0.635668,1
28,False,0.0,False,True,7,118,37,28,0,0,0,0.119398,0
29,True,0.0,False,False,7,228,58,22,0,2,1,0.635668,1
30,False,0.0,False,True,7,189,33,25,0,2,2,0.230241,0
31,False,0.0,False,True,7,118,37,28,0,0,0,0.119398,0
32,False,0.0,False,True,7,361,28,27,0,1,4,0.517708,1
33,False,0.0,False,True,7,225,28,24,0,1,2,0.253556,0
34,True,0.0,False,False,7,369,31,25,0,3,0,0.977763,1
35,True,0.0,False,False,7,289,33,30,0,2,1,0.933129,1
36,True,0.0,False,False,7,235,37,29,1,1,1,0.756842,1
37,False,0.0,False,False,7,118,40,34,0,1,8,0.002207,0
38,False,0.0,False,False,7,231,39,35,0,2,2,0.057078,0
39,False,0.0,False,False,7,179,53,25,0,1,1,0.009374,0

=================================================================================================================================================

## Installing and Importing `pymysql`

In [6]:
import pymysql

In [7]:
conn = pymysql.connect(
    host='localhost',
    user='root',
    password='Giri03@mysql',  # Still an empty string
    database='predicted_outputs'
)

In [8]:
cursor = conn.cursor()

=================================================================================================================================================

## Creating the 'predicted_outputs' table in MySQL

In [9]:
df_new_obs = model.predicted_outputs()
df_new_obs

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet,Probability,Prediction
0,False,0.0,False,True,6,179,30,19,1,0,0,0.099575,0
1,True,0.0,False,False,6,361,28,27,0,1,4,0.897216,1
2,False,0.0,False,True,6,155,34,25,0,2,0,0.256719,0
3,False,0.0,False,True,6,179,40,22,1,2,0,0.167495,0
4,True,0.0,False,False,6,155,34,25,0,2,0,0.738584,1
5,True,0.0,False,False,6,225,28,24,0,1,2,0.734205,1
6,True,0.0,False,False,6,118,46,25,0,2,0,0.564198,1
7,False,0.0,False,True,6,179,30,19,1,0,0,0.099575,0
8,False,0.0,False,True,6,118,37,28,0,0,0,0.118777,0
9,True,0.0,False,False,6,118,37,28,0,0,0,0.524395,1
10,False,0.0,False,True,6,378,36,21,0,2,4,0.466122,0
11,False,0.0,True,False,6,118,50,31,0,1,0,0.718848,1
12,False,0.0,True,False,6,233,31,21,1,1,8,0.362669,0
13,False,0.0,False,True,6,179,30,19,1,0,0,0.099575,0
14,False,0.0,False,False,6,235,48,33,0,1,5,0.012456,0
15,False,0.0,False,False,6,268,33,25,1,0,0,0.028986,0
16,False,0.0,True,False,6,118,50,31,0,1,0,0.718848,1
17,True,0.0,False,False,6,179,30,19,1,0,0,0.474962,0
18,False,0.0,False,True,6,291,40,25,0,1,1,0.399885,0
19,True,0.0,False,False,7,179,30,19,1,0,0,0.476436,0
20,False,0.0,False,True,7,118,37,28,0,0,0,0.119398,0
21,False,0.0,False,True,7,233,31,21,1,1,8,0.034260,0
22,True,0.0,False,False,7,118,37,28,0,0,0,0.525869,1
23,True,0.0,False,False,7,118,37,28,0,0,0,0.525869,1
24,False,0.0,False,True,7,233,31,21,1,1,8,0.034260,0
25,False,0.0,False,True,7,235,43,38,0,1,0,0.548212,1
26,False,0.0,True,False,7,233,31,21,1,1,8,0.364037,0
27,True,0.0,False,False,7,228,58,22,0,2,1,0.635668,1
28,False,0.0,False,True,7,118,37,28,0,0,0,0.119398,0
29,True,0.0,False,False,7,228,58,22,0,2,1,0.635668,1
30,False,0.0,False,True,7,189,33,25,0,2,2,0.230241,0
31,False,0.0,False,True,7,118,37,28,0,0,0,0.119398,0
32,False,0.0,False,True,7,361,28,27,0,1,4,0.517708,1
33,False,0.0,False,True,7,225,28,24,0,1,2,0.253556,0
34,True,0.0,False,False,7,369,31,25,0,3,0,0.977763,1
35,True,0.0,False,False,7,289,33,30,0,2,1,0.933129,1
36,True,0.0,False,False,7,235,37,29,1,1,1,0.756842,1
37,False,0.0,False,False,7,118,40,34,0,1,8,0.002207,0
38,False,0.0,False,False,7,231,39,35,0,2,2,0.057078,0
39,False,0.0,False,False,7,179,53,25,0,1,1,0.009374,0

=================================================================================================================================================

## Executing an SQL Query from Python

In [10]:
cursor.execute('SELECT * FROM predicted_outputs;')

0

In [11]:
query = 'SELECT * FROM predicted_outputs;'

In [12]:
cursor.execute(query)

0

=================================================================================================================================================

## Moving Data from Python to SQL

### Creating the INSERT Statement

In [13]:
insert_query = 'INSERT INTO predicted_outputs VALUES'

In [14]:
insert_query

'INSERT INTO predicted_outputs VALUES'

In [15]:
df_new_obs.shape

(40, 13)

In [16]:
df_new_obs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet', 'Probability', 'Prediction'], dtype=object)

In [17]:
df_new_obs['Age']

0     30
1     28
2     34
3     40
4     34
5     28
6     46
7     30
8     37
9     37
10    36
11    50
12    31
13    30
14    48
15    33
16    50
17    30
18    40
19    30
20    37
21    31
22    37
23    37
24    31
25    43
26    31
27    58
28    37
29    58
30    33
31    37
32    28
33    28
34    31
35    33
36    37
37    40
38    39
39    53
Name: Age, dtype: int64

In [18]:
for i in range(df_new_obs.shape[0]):
    insert_query += '('

    for j in range(df_new_obs.shape[1]):
        insert_query += str(df_new_obs[df_new_obs.columns.values[j]][i]) + ', '
    
    insert_query = insert_query[:-2] + '), '

In [19]:
insert_query

'INSERT INTO predicted_outputs VALUES(False, 0.0, False, True, 6, 179, 30, 19, 1, 0, 0, 0.09957536721026415, 0), (True, 0.0, False, False, 6, 361, 28, 27, 0, 1, 4, 0.8972156950053091, 1), (False, 0.0, False, True, 6, 155, 34, 25, 0, 2, 0, 0.25671906225437324, 0), (False, 0.0, False, True, 6, 179, 40, 22, 1, 2, 0, 0.16749511700823388, 0), (True, 0.0, False, False, 6, 155, 34, 25, 0, 2, 0, 0.7385841066449242, 1), (True, 0.0, False, False, 6, 225, 28, 24, 0, 1, 2, 0.734205456563895, 1), (True, 0.0, False, False, 6, 118, 46, 25, 0, 2, 0, 0.5641984364273622, 1), (False, 0.0, False, True, 6, 179, 30, 19, 1, 0, 0, 0.09957536721026415, 0), (False, 0.0, False, True, 6, 118, 37, 28, 0, 0, 0, 0.11877745949344727, 0), (True, 0.0, False, False, 6, 118, 37, 28, 0, 0, 0, 0.5243945127735318, 1), (False, 0.0, False, True, 6, 378, 36, 21, 0, 2, 4, 0.4661222061554629, 0), (False, 0.0, True, False, 6, 118, 50, 31, 0, 1, 0, 0.7188475630060766, 1), (False, 0.0, True, False, 6, 233, 31, 21, 1, 1, 8, 0.3626687364023771, 0), (False, 0.0, False, True, 6, 179, 30, 19, 1, 0, 0, 0.09957536721026415, 0), (False, 0.0, False, False, 6, 235, 48, 33, 0, 1, 5, 0.012455937828433586, 0), (False, 0.0, False, False, 6, 268, 33, 25, 1, 0, 0, 0.02898611809656749, 0), (False, 0.0, True, False, 6, 118, 50, 31, 0, 1, 0, 0.7188475630060766, 1), (True, 0.0, False, False, 6, 179, 30, 19, 1, 0, 0, 0.4749615801440482, 0), (False, 0.0, False, True, 6, 291, 40, 25, 0, 1, 1, 0.3998849756017632, 0), (True, 0.0, False, False, 7, 179, 30, 19, 1, 0, 0, 0.4764364502629957, 0), (False, 0.0, False, True, 7, 118, 37, 28, 0, 0, 0, 0.11939781363209989, 0), (False, 0.0, False, True, 7, 233, 31, 21, 1, 1, 8, 0.03425988659648701, 0), (True, 0.0, False, False, 7, 118, 37, 28, 0, 0, 0, 0.5258691400216583, 1), (True, 0.0, False, False, 7, 118, 37, 28, 0, 0, 0, 0.5258691400216583, 1), (False, 0.0, False, True, 7, 233, 31, 21, 1, 1, 8, 0.03425988659648701, 0), (False, 0.0, False, True, 7, 235, 43, 38, 0, 1, 0, 0.5482121786383495, 1), (False, 0.0, True, False, 7, 233, 31, 21, 1, 1, 8, 0.36403667964934133, 0), (True, 0.0, False, False, 7, 228, 58, 22, 0, 2, 1, 0.6356679866315383, 1), (False, 0.0, False, True, 7, 118, 37, 28, 0, 0, 0, 0.11939781363209989, 0), (True, 0.0, False, False, 7, 228, 58, 22, 0, 2, 1, 0.6356679866315383, 1), (False, 0.0, False, True, 7, 189, 33, 25, 0, 2, 2, 0.2302414481510723, 0), (False, 0.0, False, True, 7, 118, 37, 28, 0, 0, 0, 0.11939781363209989, 0), (False, 0.0, False, True, 7, 361, 28, 27, 0, 1, 4, 0.5177083296300086, 1), (False, 0.0, False, True, 7, 225, 28, 24, 0, 1, 2, 0.253556095551894, 0), (True, 0.0, False, False, 7, 369, 31, 25, 0, 3, 0, 0.9777628717211312, 1), (True, 0.0, False, False, 7, 289, 33, 30, 0, 2, 1, 0.9331288474954949, 1), (True, 0.0, False, False, 7, 235, 37, 29, 1, 1, 1, 0.7568421999946309, 1), (False, 0.0, False, False, 7, 118, 40, 34, 0, 1, 8, 0.002207326353496206, 0), (False, 0.0, False, False, 7, 231, 39, 35, 0, 2, 2, 0.057077689281478564, 0), (False, 0.0, False, False, 7, 179, 53, 25, 0, 1, 1, 0.009373873824704528, 0), '

In [20]:
insert_query = insert_query[:-2] + ';'

In [21]:
insert_query

'INSERT INTO predicted_outputs VALUES(False, 0.0, False, True, 6, 179, 30, 19, 1, 0, 0, 0.09957536721026415, 0), (True, 0.0, False, False, 6, 361, 28, 27, 0, 1, 4, 0.8972156950053091, 1), (False, 0.0, False, True, 6, 155, 34, 25, 0, 2, 0, 0.25671906225437324, 0), (False, 0.0, False, True, 6, 179, 40, 22, 1, 2, 0, 0.16749511700823388, 0), (True, 0.0, False, False, 6, 155, 34, 25, 0, 2, 0, 0.7385841066449242, 1), (True, 0.0, False, False, 6, 225, 28, 24, 0, 1, 2, 0.734205456563895, 1), (True, 0.0, False, False, 6, 118, 46, 25, 0, 2, 0, 0.5641984364273622, 1), (False, 0.0, False, True, 6, 179, 30, 19, 1, 0, 0, 0.09957536721026415, 0), (False, 0.0, False, True, 6, 118, 37, 28, 0, 0, 0, 0.11877745949344727, 0), (True, 0.0, False, False, 6, 118, 37, 28, 0, 0, 0, 0.5243945127735318, 1), (False, 0.0, False, True, 6, 378, 36, 21, 0, 2, 4, 0.4661222061554629, 0), (False, 0.0, True, False, 6, 118, 50, 31, 0, 1, 0, 0.7188475630060766, 1), (False, 0.0, True, False, 6, 233, 31, 21, 1, 1, 8, 0.3626687364023771, 0), (False, 0.0, False, True, 6, 179, 30, 19, 1, 0, 0, 0.09957536721026415, 0), (False, 0.0, False, False, 6, 235, 48, 33, 0, 1, 5, 0.012455937828433586, 0), (False, 0.0, False, False, 6, 268, 33, 25, 1, 0, 0, 0.02898611809656749, 0), (False, 0.0, True, False, 6, 118, 50, 31, 0, 1, 0, 0.7188475630060766, 1), (True, 0.0, False, False, 6, 179, 30, 19, 1, 0, 0, 0.4749615801440482, 0), (False, 0.0, False, True, 6, 291, 40, 25, 0, 1, 1, 0.3998849756017632, 0), (True, 0.0, False, False, 7, 179, 30, 19, 1, 0, 0, 0.4764364502629957, 0), (False, 0.0, False, True, 7, 118, 37, 28, 0, 0, 0, 0.11939781363209989, 0), (False, 0.0, False, True, 7, 233, 31, 21, 1, 1, 8, 0.03425988659648701, 0), (True, 0.0, False, False, 7, 118, 37, 28, 0, 0, 0, 0.5258691400216583, 1), (True, 0.0, False, False, 7, 118, 37, 28, 0, 0, 0, 0.5258691400216583, 1), (False, 0.0, False, True, 7, 233, 31, 21, 1, 1, 8, 0.03425988659648701, 0), (False, 0.0, False, True, 7, 235, 43, 38, 0, 1, 0, 0.5482121786383495, 1), (False, 0.0, True, False, 7, 233, 31, 21, 1, 1, 8, 0.36403667964934133, 0), (True, 0.0, False, False, 7, 228, 58, 22, 0, 2, 1, 0.6356679866315383, 1), (False, 0.0, False, True, 7, 118, 37, 28, 0, 0, 0, 0.11939781363209989, 0), (True, 0.0, False, False, 7, 228, 58, 22, 0, 2, 1, 0.6356679866315383, 1), (False, 0.0, False, True, 7, 189, 33, 25, 0, 2, 2, 0.2302414481510723, 0), (False, 0.0, False, True, 7, 118, 37, 28, 0, 0, 0, 0.11939781363209989, 0), (False, 0.0, False, True, 7, 361, 28, 27, 0, 1, 4, 0.5177083296300086, 1), (False, 0.0, False, True, 7, 225, 28, 24, 0, 1, 2, 0.253556095551894, 0), (True, 0.0, False, False, 7, 369, 31, 25, 0, 3, 0, 0.9777628717211312, 1), (True, 0.0, False, False, 7, 289, 33, 30, 0, 2, 1, 0.9331288474954949, 1), (True, 0.0, False, False, 7, 235, 37, 29, 1, 1, 1, 0.7568421999946309, 1), (False, 0.0, False, False, 7, 118, 40, 34, 0, 1, 8, 0.002207326353496206, 0), (False, 0.0, False, False, 7, 231, 39, 35, 0, 2, 2, 0.057077689281478564, 0), (False, 0.0, False, False, 7, 179, 53, 25, 0, 1, 1, 0.009373873824704528, 0);'

In [22]:
cursor.execute(insert_query)

40

In [23]:
conn.commit()

In [24]:
conn.close()

<hr>